### ISSUE TITLE
This requires some extra addon to work?

### ISSUE THREAD

**Issue by TitanX101** [BerkanYildiz/XenForo.NET#1]
Hello.
This requires some extra addon to work?

**Comment by BerkanYildiz** [comment]
https://xfrocks.com/resources/bd-api-for-xenforo-2-0.36/updates

**Comment by BerkanYildiz** [comment]
@Trigger-edge 
https://xfrocks.com/resources/bd-api-for-xenforo-2-0.36/updates 
https://github.com/xfrocks/bdApi/tree/xenforo2
